version: 2

jobs:
  build:
    docker:
      - image: "lballabio/boost"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install git
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Init Submodules
          command: 'git submodule init && git submodule update'
      - run:
          name: Build
          command: 'mkdir build && cd build && cmake .. && cmake --build .'
      - run:
          name: Run Unit Tests
          command: 'cd build && ctest -C Debug -V'
